### ISSUE TITLE
部署失败，求大神帮助

### ISSUE THREAD

**Issue by onlynight** [reedhong/fomo3d_clone#1]
```bash
$ truffle migrate
Compiling .\contracts\F3DexternalSettings.sol...
Using network 'development'.

Error: Could not find built Migrations contract: Could not find artifacts for Migrations from any sources
    at Object.lastCompletedMigration (C:\Users\wyndam\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-migrate\index.js:250:1)
    at Object.needsMigrating (C:\Users\wyndam\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-migrate\index.js:277:1)
    at runMigrations (C:\Users\wyndam\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\commands\migrate.js:75:1)
    at C:\Users\wyndam\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\commands\migrate.js:107:1
    at C:\Users\wyndam\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\environment.js:71:1
    at C:\Users\wyndam\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\property.js:119:1
    at C:\Users\wyndam\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\requestmanager.js:89:1
    at C:\Users\wyndam\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (C:\Users\wyndam\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\wyndam\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (C:\Users\wyndam\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\wyndam\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:509:1)
    at IncomingMessage.<anonymous> (C:\Users\wyndam\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:469:1)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

```javascript
module.exports = {
  networks: {
    development: {
      host: "127.0.0.1",
      port: 7545,
      network_id: "*" // Match any network id
    },
    develop: {
      host: "127.0.0.1",
      port: 7545,
      network_id: "*" // Match any network id
    },

    // test: {
    //   host: "127.0.0.1",
    //   port: 7545,
    //   network_id: "*" // Match any network id
    // },

    // mine: {
    //   host: "127.0.0.1",
    //   port: 8545,
    //   network_id: "*", // Match any network id
    //   gas: 4712382
    // },
    // ropsten:  {
    //   network_id: 3,
    //   host: "localhost",
    //   port:  8545,
    //   gas:   4700000
    // }
  }  
};
```

**Comment by tanhuiya** [comment]
请问 解决没？
